version: '3.9'
x-default-logging: &logging
 driver: "json-file"
 options:
   max-size: "5m"
   max-file: "2"
   tag: "{{.Name}}|{{.ImageName}}|{{.ID}}"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.55
    container_name: jaeger
    ports:
      - 6831:6831/udp
      - 16686:16686
    networks:
      - cloud-native-observability
  prometheus:
    image: prom/prometheus:v2.50.1
    container_name: prometheus
    volumes:
      - ./config/prometheus/config.yml/:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--enable-feature=exemplar-storage"
    ports:
      - 9090:9090
    networks:
      - cloud-native-observability
  opentelemetry-collector:
    user: 0:0
    image: otel/opentelemetry-collector-contrib:0.96.0
    container_name: opentelemetry-collector
    volumes:
      - ./config/collector/config.yml/:/etc/opentelemetry-collector.yml
      - ./config/collector/gateway.crt:/tmp/certs/server.crt
      - ./config/collector/gateway.key:/tmp/certs/server.key
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command:
      - "--config=/etc/opentelemetry-collector.yml"
    networks:
      - cloud-native-observability
    extra_hosts:
      - "wos.local:192.168.0.106"
    ports:
      - 4317:4317
      - 13133:13133
      - 8889:8889
    stop_grace_period: 1s
  loki:
    image: grafana/loki:2.9.5
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - cloud-native-observability
  promtail:
    image: grafana/promtail:2.9.5
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - cloud-native-observability
  grafana:
    image: grafana/grafana:10.0.12
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - cloud-native-observability
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ORG_ROLE=Editor
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

networks:
  cloud-native-observability:
